linkedpipes/applications

README.md
docker-compose.yml

Updated Quick start guide as per #30.
Please note, however, that we currently offer a docker-compose link from develop (as it's not in master branch yet) what should be resolved later on.

Updated quick start

---

src/backend/Dockerfile

See http://paulbakker.io/java/docker-gradle-multistage/

Backend Docker image tweak

---

.gitignore
docker-compose.yml

Included Openlink Virtuoso and Discovery in docker-compose

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/MapController.java
src/frontend/src/_services/discovery.service.js

- Frontend function can now be passed a filters option that get passed to the body of the request.

[Frontend][Feature] Frontend call to getMarkers can pass filters

---

src/frontend/src/components/CreateApp/CreateAppCard.jsx
src/frontend/src/components/CreateApp/CreateAppStepper.jsx
src/frontend/src/components/CreateApp/DataSourcesTable.jsx
src/frontend/src/components/CreateApp/VisualizerCard.jsx
src/frontend/src/components/CreateApp/VisualizerCardCollectionView.jsx
src/frontend/src/components/Dashboard/Dashboard.jsx
src/frontend/src/components/Navbar/NavigationBar.jsx
src/frontend/src/components/Navbar/UserDropdown/UserButton.jsx
src/frontend/src/components/Visualizers/GoogleMaps/GoogleMapsPopup.jsx
src/frontend/src/containers/AboutPage.jsx

• Includes google maps SVG icons
• Last step is now a new component (will be improved further later)
• Minor refactoring and warnings elimination

Pull request for refined stepper flow

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/services/geo/GeoService.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/ConstructSparqlQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/SelectSparqlQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/SparqlQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/geo/GeoPropertiesQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/geo/MarkerQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/visualization/ConceptsQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/visualization/SchemesQueryProvider.java

Implement `getForNamed(String)` method into queries. Construct queries using a Template Method design pattern.

[Backend][Feature] Add named graph support to query

---

.travis.yml
docker-compose.yml
src/backend/build.gradle
src/backend/src/main/config/com/linkedpipes/lpa/backend/config.properties
src/frontend/package.json
src/frontend/yarn.lock

• New travis job that uses local discovery from docker for gradle tests 
• Gradle caching on travis backend job
• Temporary solution for frontend travis yarn bug
• Updated docker compose to use discovery from linkedpipes/applications:discovery

Pull request with latest CI/CD fixes

---

README.md
docker-compose-master.yml
src/frontend/Dockerfile-prod

- Included missing files for production image of frontend

Frontend docker image for production

---

README.md
docker-compose-master.yml
docker-compose.yml
nginx-prod.conf
nginx.conf
src/backend/src/main/config/application.conf
src/backend/src/main/resources/com/linkedpipes/lpa/backend/services/virtuoso_sd.ttl
src/frontend/src/_services/discovery.service.js

• Contains all prefixes with lpa_* replaced into lpa-*

Pull request to replace export with exportWithSD frontend call

---

README.md
docker-compose-master.yml
docker-compose.yml

- No longer mounting the unused volume in backend
- Updated readme.md with latest instructions
- Modified production docker-compose-master for using the right ports.

[Deployment][Bug Fixes]

---

src/frontend/src/_services/discovery.service.js
src/frontend/src/components/SelectSources/DataSourcesTable.jsx
src/frontend/src/components/SelectSources/SelectSources.jsx

• Fixed the UI freezing bugs
• Pressing execute start loader instantly
• Pressing execute disables other buttons
• Added proper error handler for `whatwg-fetch`s `fetch` method

Pull request to add new frontend error handler

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/DiscoveryController.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/ExecutionController.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/PipelineController.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/ErrorResponse.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/exceptions/ConnectionException.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/exceptions/GlobalExceptionHandler.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/exceptions/LpAppsException.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/DiscoveryService.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/DiscoveryServiceComponent.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/EtlService.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/EtlServiceComponent.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/util/HttpRequestSender.java
src/backend/src/test/java/com/linkedpipes/lpa/backend/controllers/DiscoveryControllerTests.java
src/backend/src/test/java/com/linkedpipes/lpa/backend/util/HttpRequestSenderTests.java

- Now throwing LpAppsException to return custom errors to frontend 
- Error response to frontend is now a JSON object containing HTTP error code and error message

[Backend] [Feature] New LpApps custom exception and handling functionality

---

src/frontend/package.json
src/frontend/src/components/VisualizerController/Container/VisualizerContainer.jsx
src/frontend/src/components/Visualizers/GoogleMaps/GoogleMapsPopup.jsx
src/frontend/src/components/Visualizers/GoogleMaps/GoogleMapsVisualizer.jsx
src/frontend/yarn.lock

• OnComponentMount will iterate over created markers and fit the global view to bounds of those markers

Pull request with GoogleMaps improvements

---

src/frontend/package.json
src/frontend/yarn.lock

• Hotfix for issue discovered by Alex

Pull request with  frontend crash fix

---

src/frontend/src/components/SelectSources/SelectSources.jsx

• When user picks sources from samples widget - it no longer sends empty string

Pull request with latest frontend bug fix

---

src/backend/src/main/resources/com/linkedpipes/lpa/backend/services/base.ttl

Updated ASK query in tree map template ttl file

[Backend] [Other] Updated treemap template

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/DiscoveryController.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/PipelineController.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/database/UserDao.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/UserService.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/UserServiceComponent.java

Calling POST /api/user is no longer required now.

Integration tests fix

---

docker-compose.yml

• Minor update in docker-compose for virtuoso image. Fixes @ponsietta's issue with that container on Windows 10

[General] [Other] Updated volume for virtuoso in docker-compose

---

docker-compose-master.yml
docker-compose.yml

Passing environment to Sentry in docker-compose

[Backend] [Other] Now passing environment to sentry

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/services/ExecutorServiceComponent.java

- Only report ETL status when it finished
- Fixed typo in timeout scheduler

ETL status fix

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/ConstructSparqlQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/SelectSparqlQueryProvider.java

Replaced FROM NAMED with FROM in SPARQL queries

[Backend] [Bug Fix] Bug fix in SPARQL query providers

---

docker-compose-master.yml
docker-compose.yml

If anyone is available, please approve the PR

[Deployment] Minor virtuoso tweaks to attempt to fix graph freezing

---

.gitignore
.travis.yml
docker-compose-master.yml
docker-compose.yml
src/backend/build.gradle
src/backend/src/main/config/application.properties
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/database/ApplicationDao.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/database/DiscoveryDao.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/database/ExecutionDao.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/database/UserDao.java
src/backend/src/main/resources/db/migration/V1.0__Create_schema.sql

Instead of dropping and recreating the database each time we boot backend, we now maintain a set of DB migration scripts and use Flyway for database migration.
**What does it mean?**
1.  The database is not wiped every time backend is restarted, nor is re-created automatically.
2. If you run docker-compose, you don't have to worry about anything.
3. The local database must be maintained:
a. to get up-to-date just run: `./gradlew flywayMigrate` (better always after checking out new code from git)
b. if you want to wipe your local data just run: `./gradlew flywayClean flywayMigrate` (assuming you want to get back to the consistent schema)
4. If you don't have a consistent DB locally, the backend will refuse to start, run `./gradlew flywayMigrate` to get up-to-date.
5. If we touch backend DB …

Database migrations

---

.travis.yml

Every push on every branch triggers build stage to check whether code compiles on both backend and frontend

PR with more strict travis setup checking build on every push

---

.gitignore
.travis.yml
src/tests/browserstack_plugins/fast_selenium.py
src/tests/e2e_tests.py
src/tests/requirements.txt

• More tests later
• Whoever available please approve this asap

PR with complete CI setup for automated GMaps flow testing

---

src/backend/src/main/java/com/linkedpipes/lpa/backend/controllers/MapVisualizerController.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/entities/geo/Marker.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/services/geo/GeoService.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/extractors/geo/MarkerExtractor.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/ConstructSparqlQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/geo/GeoPropertiesQueryProvider.java
src/backend/src/main/java/com/linkedpipes/lpa/backend/sparql/queries/geo/MarkerQueryProvider.java

Now passing an array of localised labels with each marker
@aorumbayev you will need to change the way you read the label from the data, if you using it.

[Backend] [Bugfix] Fixed issue of duplicate map markers due to labels

---

src/frontend/src/components/Visualizers/Chord/ChordVisualizer.jsx
src/frontend/src/containers/CreateVisualizerPage/children/Container/VisualizerContainer.jsx
src/frontend/src/containers/CreateVisualizerPage/children/Filters/children/ChordFilter/ChordFiltersComponent.jsx
src/frontend/src/containers/DiscoverPage/DiscoverVisualizerPicker/children/DiscoverVisualizerCardContainer.jsx
src/frontend/src/layouts/PrivateLayout/PrivateLayout.jsx

- Removed padding from Chord SVG that was causing page to stretch till end
- Added padding to main tag so it is more visually appealing

[Frontend] Minor UI fixes/improvements

---

src/frontend/src/containers/DiscoverPage/DiscoverVisualizerPicker/children/DiscoverVisualizerCardComponent.jsx
src/frontend/src/containers/DiscoverPage/DiscoverVisualizerPicker/children/DiscoverVisualizerCardContainer.jsx

[Frontend] Card wont trigger action after being clicked once
